name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main # Or your deployment branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write' # Required for Workload Identity Federation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GIT_SA_KEY}}'
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify authentication
        run: |
          gcloud auth list
          gcloud config list project

      - name: Submit build to Google Cloud Build
        run: |
          gcloud builds submit . \
            --config=infrastructure/cloudbuild.yaml \
            --substitutions=COMMIT_SHA=${{ github.sha }}
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      # Optional: Clear credentials after use
      - name: 'Cleanup'
        if: always()
        run: |
          if [ -f "${{ steps.auth.outputs.credentials_file_path }}" ]; then
            rm "${{ steps.auth.outputs.credentials_file_path }}"
          fi 